spring:
  application:
    name: ppt-to-video-converter
  autoconfigure:
    mvc:
      static-path-pattern: /**
    resources:
      static-locations:
        - classpath:/static/
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

logging:
  level:
    root: INFO
    ai.bluefields.aipresenter: DEBUG
    org.springframework.web: INFO